export const routes = [{
  route_id: 1,
  route_name: "Hapugala-Unawatuna",
  day: 1
}, {
  route_id: 2,
  route_name: "Baddegam-Poddala",
  day: 2
}, {
  route_id: 3,
  route_name: "Thalapitiya-Kaluwella",
  day: 3
}, {
  route_id: 4,
  route_name: "Ginthota-Baddegama",
  day: 4
}, {
  route_id: 5,
  route_name: "Hapugala-Unawatuna",
  day: 5
}, {
  route_id: 6,
  route_name: "Baddegam-Poddala",
  day: 6
}, {
  route_id: 7,
  route_name: "Thalapitiya-Kaluwella",
  day: 7
}, {
  route_id: 8,
  route_name: "Ginthota-Baddegama",
  day: 8
}, {
  route_id: 9,
  route_name: "Hapugala-Unawatuna",
  day: 9
}, {
  route_id: 10,
  route_name: "Baddegam-Poddala",
  day: 10
}, {
  route_id: 11,
  route_name: "Thalapitiya-Kaluwella",
  day: 11
}, {
  route_id: 12,
  route_name: "Ginthota-Baddegama",
  day: 12
}, {
  route_id: 13,
  route_name: "Thalapitiya-Kaluwella",
  day: 13
}, {
  route_id: 14,
  route_name: "Ginthota-Baddegama",
  day: 14
}

];